name: my_activity
description: A secure activity tracking application implementing OWASP MSTG.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^3.0.7
  logger: ^2.0.1
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  fl_chart: ^0.63.0
  flutter_local_notifications: ^15.1.0+1
  # Security Dependencies
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  http: ^0.13.5
  encrypt: ^5.0.3
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  flutter_jailbreak_detection: ^1.9.0
  dio: ^5.4.0  # For SSL pinning and secure HTTP requests
  flutter_windowmanager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Security Testing Dependencies
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  custom_lint: ^0.5.8
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  sqflite_common_ffi: ^2.3.2+1  # For testing database operations

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
