name: my_activity
description: A Flutter application for tracking and managing daily activities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.8.3
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.2.1
  http: ^1.2.1
  pocketbase: ^0.19.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
